
POST http://localhost:3000/user
content-Type: application/json

{
    "name": "qwewqe",
    "email": "rr112te2st1@gmail.com",
    "password": "qwetest",
    "isActive": true
}

####

GET http://localhost:3000/user

###

GET http://localhost:3000/user/11

####

DELETE http://localhost:3000/user/2

###################################

PATCH http://localhost:3000/user/1
content-Type: application/json

{
    "name": "qweq2",
    "email": "q@gmail.com",
    "isActive": false
    
}


################- POSTGRESSQL - #################

POST http://localhost:3000/temp
content-Type: application/json

{
    "name": "RENNER2",
    "email": "rrTST@gmail.com"
}

##############
GET http://localhost:3000/temp

##############

GET http://localhost:3000/temp/1

##############

DELETE http://localhost:3000/temp/4

##############

PATCH http://localhost:3000/temp/1
content-Type: application/json

{
    "name": "Raulv2 rennev3v3r",
    "email": "test21111@gmail.com"
}